import * as React from 'react';

import { getHead } from '../components/Article';
import Demo from '../components/Demo';
import Roles from '../components/Roles';
import { demos } from '../config/data';
import evondosLogo from '../images/evondos.png';
import evondosFlow from '../images/evondos-flow.png';
import evondosAino from '../images/evondos-aino.png';
import evondosTietoEvry from '../images/evondos-on-tietoevry.png';

export function Head() {
  const title = <title>FHIR Demo 2025: Evondos</title>;
  return getHead({ title });
};

export default function Evondos({ location }) {
  const roles = demos.evondos.roles;
  
  return (
    <Demo roles={roles} location={location}>
      <h1 className="white">
        <a href="https://www.evondos.com/">
          <img src={evondosLogo} alt="Evondos" />
        </a>
      </h1>
      <Roles list={roles} />
      <section id="about">
        <h2>An Automatic Medicine Dispensing Robot and Service</h2>
        <p>
          The Evondos® Service consists of the medicine dispensing robot, Telecare system, customer
          care, and other service elements, for example, support and training. The automated
          medicine dispensing (AMD) system has been designed to meet the needs of home care
          clients, the elderly, or other home care clients, and the professional care organizations
          that serve them.
        </p>
        <p>
          The Evondos service ensures a high standard of pharmacotherapy guiding homecare clients
          in always taking the correct medicine in the prescribed dose at the right time. The
          automated medication service uses prepacked multi-dose medicine pouches provided by a
          pharmacy.
        </p>
        <p>
          The care organization and care staff may monitor the progress of pharmacotherapy in
          real-time from the Telecare system, and remotely using a mobile phone application.
        </p>
        <p>
          Evondos®E300, Evondos®Anna and Evondos®Telecare systems are all CE-marked according to
          the European MDR directive. 
        </p>
      </section>
      <section id="hackathon">
        <h2>NORDIC HACKATHON 2025 – Evondos & Arne taking his medication in his home</h2>
        <p>
          Evondos participated in the <a href="https://nordichackathon.blogs.dsv.su.se/"
          >Nordic Hackathon for Interoperability in Coordinated Health and Social Care</a>,
          organised by Stockholm University and Karolinska Institutet and supported by Health Data
          Sweden.
        </p>
        <img
          src={evondosAino}
          alt=""
        />
        <h3>User story</h3>
        <p>
          Evondos is a company providing automated medicine dispensing for Arne in his home. The
          care givers for Arne want to see the client status in one system, including if Arne has
          taken his medicine or not. Medication deviations (not taking medication, or taking double
          medication) leads to unnecessary hospitalization and generates unnecessary illness, but
          also unnecessary expenses for hundreds of millions of Euros in Nordics.
        </p>
        <img
          src={evondosFlow}
          alt="Evondos medication dispensation robot sends medication events to Integration Engine that forwards them to FHIR Server. Multiple solutions, including TietoEvry journal view and Inera implementation interact with the FHIR server."
        />
        <h3>Hackathon accomplishments</h3>
        <p>
          Learn more about the Evondos solution on the <a
          href="https://www.evondos.com/our-service/municipality/how-it-works">How it
          works</a> page on Evondos web site.
        </p>
        <p>
          Evondos delivers medication taken and medication not taken information to FHIR server
          that is available for the consumption of multiple willing partners! For example TietoEvry
          displayed this in an intuitive visual format for Caregiver to read.
        </p>
        <img
          src={evondosTietoEvry}
          alt="Medication dispensation events generated by Evondos robot shown on TietoEvry view"
        />
       <h3>What problem were you trying to solve?</h3>
        <p>
          Provide meaningful information of a client home care medication status & contact request
          in relevant system for caregiver to assess.
        </p>
        <h3>What is the greatest aha moment?</h3>
        <p>
          There are multiple ways to utilize FHIR server data and it is very accessible for all to
          consume!
        </p>
        <h3>What has been the greatest hurdle along the way? Was it solved? How?</h3>
        <p>
          The greatest hurdle was to agree on data notations and formatting in a situation that
          there exists multiple good solutions. The agreement was found through discussion with
          multiple partners and agreeing that there are also other good ways to do it and this time
          it is applied in this way.
        </p>
        <h3>What was the result/outcome?</h3>
        <p>
          Result was an integration all the way from physical Evondos Anna dispenser to a
          custom-made TietoEvry view to display the medication adherence and history of medication
          events and in addition the delivery of Arne wishing for caregiver contact in a form of
          appointment request to be consumed from FHIR server i.e. in INERA solution.
        </p>
        <h3>What should the next step be?</h3>
        <p>
          Test use the integration and visual representation with a real customer with experience
          in both systems to provide feedback for enhancing the data flow and display.
        </p>
        <h3>What dis you take with you from the Hackathon?</h3>
        <p>
          Insipiration to really solve the data flow problems that restrict the client care today!
        </p>
      </section>
      <section id="contact">
        <h3>Contact</h3>
        <div className="business-card">
          <h3>Iikka Luosa</h3>
          <p>Integration product manager</p>
          <address>
            <a href="mailto:iikka.luosa@evondos.com">iikka.luosa@evondos.com</a>
          </address>
        </div>
      </section>
    </Demo>
  );
};
